// Pure lyric + quality utilities ported VERBATIM from the monolith (DATA-01).
//   parseLRC          ← legacy/index.html:2517-2533
//   inferQualityFromUrl ← legacy/index.html:1747-1758
// The legacy neteaseQualityToTag / kuwoQualityToTag helpers are intentionally NOT
// ported (marked 暂时保留不再使用 / "kept but unused" in the monolith).

export interface LyricLine {
	time: number;
	text: string;
	/** True when this line was generated by splitting a parenthesized clause out of its
	 *  parent line (the second-language version that came tagged inline). The renderer can
	 *  hide its translation when settings.lyricsHideParenTranslation is true. */
	fromParen?: boolean;
}

export interface QualityInfo {
	tag: string | null;
	label: string;
}

/**
 * Parse `[mm:ss.xxx]` LRC text into a time-sorted `{time,text}[]` (seconds).
 * Blank lines and lines with no timestamp are dropped. Ported verbatim from
 * legacy/index.html:2517-2533.
 */
export function parseLRC(txt: string): LyricLine[] {
	if (!txt) return [];
	const lines = txt.split(/\r?\n/);
	const reg = /\[(\d{1,2}):(\d{1,2})(?:\.(\d{1,3}))?\]/;
	const out: LyricLine[] = [];
	for (const line of lines) {
		const m = reg.exec(line);
		if (!m) continue;
		const min = parseInt(m[1], 10) || 0;
		const sec = parseInt(m[2], 10) || 0;
		const ms = m[3] ? parseInt(m[3].padEnd(3, '0'), 10) : 0;
		const time = min * 60 + sec + ms / 1000;
		const text = line.replace(reg, '').trim();
		if (text) out.push({ time, text });
	}
	out.sort((a, b) => a.time - b.time);
	return out;
}

/**
 * Split a line containing one or more `(...)` / `（...）` clauses into separate LyricLine
 * entries that share the same timestamp. Useful when the upstream LRC encodes a translated
 * version inline next to the original — the user wants the translation to live on its own
 * line so the per-part translation pipeline can process it independently (English original
 * stays as-is when English is whitelisted; the parenthesised simplified-Chinese clause is
 * still translated to the user's target language). Lines without parens pass through
 * untouched. The returned entries carry `fromParen: true` for clauses that were extracted
 * out of their parent so the renderer can optionally hide their translations.
 *
 * Conventions:
 * - Both ASCII `()` and full-width `（）` parens are recognised.
 * - A line that is ALREADY only a parenthesised clause (e.g. `(我們可以...)`) is treated as a
 *   normal line — no split, no `fromParen` flag.
 * - Multiple parens in one line produce multiple sibling entries.
 * - The order is preserved: parent (parens stripped) first, then each clause in order.
 */
export function splitParenLines(lines: LyricLine[]): LyricLine[] {
	const out: LyricLine[] = [];
	const parenRe = /[(（]([^()（）]+)[)）]/g;
	for (const line of lines) {
		const matches = [...line.text.matchAll(parenRe)];
		if (!matches.length) {
			out.push(line);
			continue;
		}
		const stripped = line.text.replace(parenRe, '').replace(/\s+/g, ' ').trim();
		// If the WHOLE line is one paren clause + nothing else, don't split — render as-is.
		if (!stripped) {
			out.push(line);
			continue;
		}
		out.push({ time: line.time, text: stripped });
		for (const m of matches) {
			const inner = (m[1] ?? '').trim();
			if (inner) out.push({ time: line.time, text: inner, fromParen: true });
		}
	}
	return out;
}

/**
 * Infer a quality tag/label from an audio URL's file extension. Lossless extensions
 * → LOSSLESS; everything else → 320K. Ported verbatim from legacy/index.html:1747-1758.
 */
export function inferQualityFromUrl(url: string | null): QualityInfo {
	if (!url) return { tag: null, label: '' };
	const base = url.split('?')[0].toLowerCase();
	const m = base.match(/\.([a-z0-9]+)$/);
	const ext = m ? m[1] : '';
	const losslessExts = ['flac', 'wav', 'ape', 'alac', 'aiff'];
	if (losslessExts.includes(ext)) {
		return { tag: 'lossless', label: 'LOSSLESS' };
	}
	// 其他一律当作 320K 显示 — everything else displays as 320K.
	return { tag: '320k', label: '320K' };
}
